### ISSUE TITLE
Not showing deeper levels as columns. Also .count() problem.

### ISSUE THREAD

**Issue by ryantnedbank** [AbsaOSS/cobrix#2]
I managed to get it working.
However, it is only showing the level 01 records as columns in the data frame.
Why is that?  The level 05 and level 10 are not appearing as columns.
Also, a .count() function is failing due to some Java error.  Why is this? (error pasted at the bottom of this issue)

scala> :load /home/private/Documents/SparkSQLExample_cobol.scala
Loading /home/private/Documents/SparkSQLExample_cobol.scala...
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.types._
import org.apache.spark.sql.{Row, DataFrame, SQLContext}
import org.apache.spark.sql.SQLContext
import za.co.absa.cobrix._
import scodec.bits._
import scodec.codecs._
spark: org.apache.spark.sql.SparkSession.type = org.apache.spark.sql.SparkSession$@4ad3969
res0: spark.Builder = org.apache.spark.sql.SparkSession$Builder@7ec5aad
res1: spark.Builder = org.apache.spark.sql.SparkSession$Builder@7ec5aad
2018-10-03 14:52:31 WARN  SparkSession$Builder:66 - Using an existing SparkSession; some configuration may not take effect.
res2: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@65f470f8
warning: there was one deprecation warning; re-run with -deprecation for details
sqlContext: org.apache.spark.sql.SQLContext = org.apache.spark.sql.SQLContext@21ed4a51
2018-10-03 14:52:40 WARN  ObjectStore:568 - Failed to get database global_temp, returning NoSuchObjectException
DataFrame: org.apache.spark.sql.DataFrame = [SAM010A_LEADER_RECORD: struct<SAM010A_ALL_ZEROS: string, SAM010A_DATE_CREATED: int ... 3 more fields>, SAM010D_DATA_RECORD_B: struct<SAM010D_ACCOUNT_NO: bigint, SAM010D_ACCOUNT_NO_A: struct<SAM010D_PREFIX: int, SAM010D_BRANCH_NO: int ... 1 more field> ... 301 more fields> ... 2 more fields]
+---------------------+---------------------+-----------------------------+----------------------+
|SAM010A_LEADER_RECORD|SAM010D_DATA_RECORD_B|SAM010E_BRANCH_TRAILER_RECORD|SAM010F_TRAILER_RECORD|
+---------------------+---------------------+-----------------------------+----------------------+
| [0000000000000000...| [2001001355, [2, ...|         [2, 1, 2408,,, 0,...|        [909000000, 0]|
| [8909000000000002...| [9909000000, [9, ...|         [2, 909, 0,, 2000...|                  [0,]|
| [0000000000000000...| [0, [0, 0, 0], [0...|         [0, 0, 0, 0.00, 9...|              [, 1725]|
| [00{0000000019640...| [, [0,, 0], [0], ...|         [0,, 0, 338520000...|                [0, 0]|
| [0000000000000000...| [0, [0, 0, 0], [0...|         [0, 0, 0, 0.00, 0...|           [, 5463696]|
| [283261{000000000...| [, [0, 147,], [1]...|         [0, 0,, 0.00, 0, ...|                [0, 0]|
| [0000000000000000...| [5000000, [0, 5, ...|         [0, 0, 0, 1000600...|                 [90,]|
| [0000000090000000...| [90, [0, 0, 90], ...|         [0, 0, 90, 0.00, ...|                [0, 0]|
| [0000000000000000...| [0, [0, 0, 0], [0...|         [0, 0, 0, 0.00, 0...|                [0, 0]|
| [0000000000000000...| [0, [0, 0, 0], [0...|         [0, 0, 0, 0.00, 0...|                [0, 0]|
+---------------------+---------------------+-----------------------------+----------------------+
only showing top 10 rows

scala> DataFrame.count()
[Stage 1:========================================================>(77 + 1) / 78]2018-10-03 15:03:30 ERROR Executor:91 - Exception in task 77.0 in stage 1.0 (TID 78)
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.apache.spark.input.FixedLengthBinaryRecordReader.nextKeyValue(FixedLengthBinaryRecordReader.scala:118)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:214)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yruslan** [comment]
Cobrix tries to retain the original COBOL schema when reading copybook+data file. That's why all the root level fields are struct types. You can use `.option("schema_retention_policy", "collapse_root")` to expand the root level of the schema. If you need a completely flat schema you can use `SparkUtils.flattenSchema()` function.

If you want to retain the structured nature of the data the better way to look at it is by exporting to json. Something like `df.toJSON.take(10).foreach(println)`

The error message is likely related to the fact the the record length does not divide the size of the binary file. Internally Cobrix uses Spark's `binaryRecords()` method. It requires that the total size of the file(s) be evenly divided by record size. The record size is available from the logs (the layout positions part). 

Usually this error means that the copybook doesn't match the data. For instance, the copybook has missing fields. You can verify this by carefully comparing first several records reported by Spark against values shown in the mainframe.
