### ISSUE TITLE
antlr4 User class threw exception: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by mpisu** [AbsaOSS/cobrix#232]
spark version 2.1.0.cloudera1
     Scala version 2.11.8 

 version cobrix-spark spark-cobol-1.0.1.jar and cobol-parser-1.0.1.jar 

Help me !!!!!!!!!!!!!

**Error :**
User class threw exception: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at za.co.absa.cobrix.cobol.parser.antlr.ANTLRParser$.parse(ANTLRParser.scala:64)
	at za.co.absa.cobrix.cobol.parser.CopybookParser$.parseTree(CopybookParser.scala:97)
	at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.loadCopyBook(FixedLenNestedReader.scala:90)
	at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.<init>(FixedLenNestedReader.scala:53)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createFixedLengthReader(DefaultSource.scala:88)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.buildEitherReader(DefaultSource.scala:75)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:60)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:48)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
	at com.datalabas.ebcdic.spark.NewStartEbcdicVariable$.main(NewStartEbcdicVariable.scala:181)
	at com.datalabas.ebcdic.spark.NewStartEbcdicVariable.main(NewStartEbcdicVariable.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:646)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153)
	at za.co.absa.cobrix.cobol.parser.antlr.copybookLexer.<clinit>(copybookLexer.java:840)
	... 18 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).

**Comment by Zejnilovic** [comment]
Hello, I am not a maintainer of this project but please have a look at [Requirements](https://github.com/AbsaOSS/cobrix#requirements) of this library.

Scala version seems fine, but spark version seems off (too small).

**Comment by mpisu** [comment]
Hi , my version spark is spark version 2.1.0 ,is not possible to change version

**Comment by Zejnilovic** [comment]
Well you can try fork cobrix and make it work with lower version of ANTLR. Then again, this might not be the only dependency that will not work with 2.1.X

**Comment by tr11** [comment]
This is due to a mismatch in the ANTLR parser version and Spark. Spark 2.1 uses version 4.5.3 and if I'm not mistaken, we're using 4.7.2.

I'm not sure whether it will work, but you can try building the cobol-parser with a lower version that works with Spark 2.1.
