### ISSUE TITLE
Unicode support with PIC N notation

### ISSUE THREAD

**Issue by schaloner-kbc** [AbsaOSS/cobrix#260]
## Question
We are reading in COBOL files and are encountering an issue with unicode definitions in the copybooks.

```
      ******************************************************************        
      * COBOL DECLARATION FOR VIEW  XXXXXXXX                           *        
      ******************************************************************        
       01  YYYYYYYY-YYY.                                                        
         10  ZZZ-ZZZZZZ                      PIC N(4). 
         ... more lines
```

This results in an error:
```
Syntax error in the copybook at line 5: Invalid input 'N' at position 5:49
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 5: Invalid input 'N' at position 5:49
	at za.co.absa.cobrix.cobol.parser.antlr.ThrowErrorStrategy.recover(ANTLRParser.scala:33)
	at za.co.absa.cobrix.cobol.parser.antlr.copybookParser.pic(copybookParser.java:2469)
	at za.co.absa.cobrix.cobol.parser.antlr.copybookParser.primitive(copybookParser.java:2791)
	at za.co.absa.cobrix.cobol.parser.antlr.copybookParser.item(copybookParser.java:3015)
	at za.co.absa.cobrix.cobol.parser.antlr.copybookParser.main(copybookParser.java:214)
	at za.co.absa.cobrix.cobol.parser.antlr.ANTLRParser$.parse(ANTLRParser.scala:72)
	at za.co.absa.cobrix.cobol.parser.CopybookParser$.parseTree(CopybookParser.scala:124)
	at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.loadCopyBook(FixedLenNestedReader.scala:96)
	at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.<init>(FixedLenNestedReader.scala:57)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createFixedLengthReader(DefaultSource.scala:88)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.buildEitherReader(DefaultSource.scala:75)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:60)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:48)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
```

According to [this](https://www.ibm.com/support/knowledgecenter/SS6SG3_6.1.0/pg/tasks/tpuni11.html), the copybook is valid.

Are there any plans to support this notation?

Thanks,
Steve

**Comment by yruslan** [comment]
It seems very easy to do since `UTF-16` is a widely supported standard. We should definitely add support for this.
In your case, `PIC N(4)` has the size of `8`, right?

Could I ask you to provide a small example (with just a couple of fields) of a data file and a copybook? It could speed things up significantly.

**Comment by schaloner-kbc** [comment]
I'm adding the necessary support at the moment.  I'll prepare a PR for this, with supporting data and send it over.

**Comment by schaloner-kbc** [comment]
> In your case, PIC N(4) has the size of 8, right?

Right

**Comment by yruslan** [comment]
That's great! Thanks!

**Comment by yruslan** [comment]
Now that support is added from the parser side, adding support for the decoder.

**Comment by yruslan** [comment]
Hi @schaloner-kbc,

Is the data with `N` encoding in big-endian or little-endian UTF-16? Or it can be either?

**Comment by tr11** [comment]
According to https://www.ibm.com/support/knowledgecenter/en/SS6SG3_6.1.0/pg/concepts/cpuni01.html, it can be either.

**Comment by yruslan** [comment]
Cool, Thanks! Adding support both with `BE` being the default.

**Comment by schaloner-kbc** [comment]
Good catch.  I hadn't considered that.  Think I've found another edge case (unrelated to PIC N) that I'm working on now.

**Comment by yruslan** [comment]
This has been released as a snapshot.
You can control the byte order using this option:
```
.option("is_utf16_big_endian", "true") // big endian UTF-16
```
In order to use it you need to do the following:
1. Add this profile to your POM file to enable snapshot versions
```
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

2. Use the latest snapshot version of Cobrix
```
<dependency>
    <groupId>za.co.absa.cobrix</groupId>
    <artifactId>spark-cobol_2.11</artifactId>
    <version>2.0.5-SNAPSHOT</version>
</dependency>
```
