### ISSUE TITLE
java.lang.ClassCastException: za.co.absa.cobrix.cobol.parser.ast.Primitive cannot be cast to za.co.absa.cobrix.cobol.parser.ast.Group

### ISSUE THREAD

**Issue by kaikilidev** [AbsaOSS/cobrix#306]
## Background [Optional]
A clear explanation of the reason for raising the question. 
This gives us a better understanding of your use cases and how we might accommodate them.

## Question
Spark shell start with following code. I can see all the jars in environment.
**spark-shell --jars /root/spark-2.4.6-bin-hadoop2.7/jars/cobol-parser_2.11-2.1.0.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/scodec-bits_2.11-1.1.4.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/scodec-core_2.11-1.10.3.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/spark-cobol_2.11-2.1.0.jar**

**val df = spark.read.format("cobol").option("copybook", "/test/cobol/sample_mainframe_fd_data_copybook.cob").load("/test/cobol/data/emp.data")** 

above step got failed with below error. Please could you help what's going wrong here..

_java.lang.ClassCastException: za.co.absa.cobrix.cobol.parser.ast.Primitive cannot be cast to za.co.absa.cobrix.cobol.parser.ast.Group_
  at za.co.absa.cobrix.cobol.parser.Copybook$$anonfun$3.apply(Copybook.scala:256)
  at za.co.absa.cobrix.cobol.parser.Copybook$$anonfun$3.apply(Copybook.scala:252)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at za.co.absa.cobrix.cobol.parser.Copybook.generateRecordLayoutPositions(Copybook.scala:252)
  at za.co.absa.cobrix.spark.cobol.schema.CobolSchema.createSparkSchema(CobolSchema.scala:78)
  at za.co.absa.cobrix.spark.cobol.schema.CobolSchema.sparkSchema$lzycompute(CobolSchema.scala:56)
  at za.co.absa.cobrix.spark.cobol.schema.CobolSchema.sparkSchema(CobolSchema.scala:56)
  at za.co.absa.cobrix.spark.cobol.schema.CobolSchema.getSparkSchema(CobolSchema.scala:69)
  at za.co.absa.cobrix.spark.cobol.reader.VarLenNestedReader.getSparkSchema(VarLenNestedReader.scala:51)
  at za.co.absa.cobrix.spark.cobol.source.CobolRelation.schema(CobolRelation.scala:82)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 49 elided

**Comment by yruslan** [comment]
Hi, Looks like there is something in the copybook that we haven't encountered yet in our use cases. Maybe a field is a GROUP but it is also a primitive. Could I ask you to share a copybook on which it happens?

**Comment by syerragunta** [comment]
Thanks for the response. I think I am using incorrect data. Later I have used proper data. its working fine.

**Comment by akhilgarg140290** [comment]
What was incorrect in data, Can you give some idea about it?
