### ISSUE TITLE
Unable to run example out of the box

### ISSUE THREAD

**Issue by caveman-bob** [AbsaOSS/cobrix#327]
I have built a VM with all the prerequisites and wanted to see the execution of the example bundled in the repository.

I have successfully built the software but receive an error when executing it.

see execution logs below
`
spark-shell --jars spark-cobol-app/target/spark-cobol-app-0.0.1-SNAPSHOT.jar
20/10/21 19:39:11 WARN Utils: Your hostname, localhost.localdomain resolves to a loopback address: 127.0.0.1; using 192.168.190.133 instead (on interface eth0)
20/10/21 19:39:11 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
20/10/21 19:39:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://192.168.190.133:4040
Spark context available as 'sc' (master = local[*], app id = local-1603334356697).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.1
      /_/
         
Using Scala version 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.read.format("cobol").option("copybook", "example_data/companies_copybook.cpy")
res0: org.apache.spark.sql.DataFrameReader = org.apache.spark.sql.DataFrameReader@55cbbf15

scala> val df = spark.read.format("cobol").option("copybook", "example_data/companies_copybook.cpy").load("example_data/companies_data/COMP.DETAILS.SEP30.DATA.dat")
java.lang.NoClassDefFoundError: scala/Product$class
  at za.co.absa.cobrix.cobol.parser.policies.CommentPolicy.<init>(CommentPolicy.scala:19)
  at za.co.absa.cobrix.spark.cobol.parameters.CobolParametersParser$.parseCommentTruncationPolicy(CobolParametersParser.scala:135)
  at za.co.absa.cobrix.spark.cobol.parameters.CobolParametersParser$.parse(CobolParametersParser.scala:226)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:55)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:47)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:232)
  ... 47 elided
Caused by: java.lang.ClassNotFoundException: scala.Product$class
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 58 more

scala> 
`

I would like to ask if I am doing something incorrectly or if this is a known issue and does it have a work around?

Thanks!

**Comment by caveman-bob** [comment]
got a little further. looks like NoClassDefFoundError: scala/Product$class is the result of incompatible scala versions.  I was rushed when I was building this so that makes sense.   I've updated the pom and I can build now and have been able to execute one of the examples...
