### ISSUE TITLE
How to handle field which is a GROUP but it is also a primitive

### ISSUE THREAD

**Issue by avinashmakey** [AbsaOSS/cobrix#386]
Spark shell start with following code. I can see all the jars in environment.
spark-shell --jars /root/spark-2.4.6-bin-hadoop2.7/jars/cobol-parser_2.11-2.1.0.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/scodec-bits_2.11-1.1.4.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/scodec-core_2.11-1.10.3.jar,/root/spark-2.4.6-bin-hadoop2.7/jars/spark-cobol_2.11-2.1.0.jar

val df = spark.read.format("cobol").option("copybook", "/test/cobol/sample_mainframe_fd_data_copybook.cob").load("/test/cobol/data/emp.data")

above step got failed with below error. Please could you help what's going wrong here..

java.lang.ClassCastException: za.co.absa.cobrix.cobol.parser.ast.Primitive cannot be cast to za.co.absa.cobrix.cobol.parser.ast.Group
at za.co.absa.cobrix.cobol.parser.Copybook$$anonfun$3.apply(Copybook.scala:256)
at za.co.absa.cobrix.cobol.parser.Copybook$$anonfun$3.apply(Copybook.scala:252)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

**Comment by avinashmakey** [comment]
Snippet of the copybook

10  :WS:-SVES-DATA                    PIC X(22).                 
               10  :WS:-FCR-CNTL-AREA REDEFINES :WS:-SVES-DATA.                 
                   15  :WS:-SSN-MTCH-CD              PIC X(1).                  
                   15  :WS:-ORIG-SSN                 PIC X(9).                  
                   15  :WS:-SUBM-DOB.                                           
                       20 :WS:-SUBM-DOB-CC           PIC X(02).                 
                       20 :WS:-SUBM-DOB-YY           PIC X(02).                 
                       20 :WS:-SUBM-DOB-MM           PIC X(02).                 
                       20 :WS:-SUBM-DOB-DD           PIC X(02).
