### ISSUE TITLE
record_format VB fails with invalid BDW block length

### ISSUE THREAD

**Issue by mark-weghorst** [AbsaOSS/cobrix#434]
## Describe the bug
When parsing a variable block format file, the Spark job abnormally terminates with an illegalStateException due to the size of the BDW block exceeding the defined maximum.  This is because when the ctx.inputStream.offset is advanced using ctx.inputStream.next(n), it lands on the RDW and not the BDW. 

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, fff32e3a8cbc, executor driver): java.lang.IllegalStateException: The length of BDW block is too big. Got 1895093475. Header: 240,244,212,227, offset: 29778.
	at za.co.absa.cobrix.cobol.reader.recordheader.RecordHeaderDecoderCommon.reportTooLargeBlockLength(RecordHeaderDecoderCommon.scala:53)
	at za.co.absa.cobrix.cobol.reader.recordheader.RecordHeaderDecoderBdw.validateBlockLength(RecordHeaderDecoderBdw.scala:86)
	at za.co.absa.cobrix.cobol.reader.recordheader.RecordHeaderDecoderBdw.getRecordLength(RecordHeaderDecoderBdw.scala:48)
	at za.co.absa.cobrix.cobol.reader.extractors.raw.VariableBlockVariableRecordExtractor.readNextBlock(VariableBlockVariableRecordExtractor.scala:41)
	at za.co.absa.cobrix.cobol.reader.extractors.raw.VariableBlockVariableRecordExtractor.hasNext(VariableBlockVariableRecordExtractor.scala:28)
	at za.co.absa.cobrix.cobol.reader.index.IndexGenerator$.sparseIndexGenerator(IndexGenerator.scala:74)
	at za.co.absa.cobrix.cobol.reader.VarLenNestedReader.generateIndex(VarLenNestedReader.scala:184)
	at za.co.absa.cobrix.spark.cobol.source.index.IndexBuilder$.generateIndexEntry(IndexBuilder.scala:163)
	at za.co.absa.cobrix.spark.cobol.source.index.IndexBuilder$.$anonfun$buildIndexForVarLenReader$2(IndexBuilder.scala:129)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1371)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1298)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1362)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1186)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:360)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:311)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

## To Reproduce

1. Use a big-endian VB formatted data file that contains at least 2 BDW's

## Expected behaviour
After advancing to the second block of records, the ctx.inputStream.offset should land on the first byte of the RDW not on the BDW.

**Comment by mark-weghorst** [comment]
After spending some time in the debugger, I have concluded that this is not a bug and is rather a configuration error.  

The solution is to add the following configuration item:

.option("bdw_adjustment", -4)

For anyone who comes across this issue and is trying to read VB data files, here is an example of a working configuration:

 ```
     fileHeaderData = spark.read
        .format("cobol")
        .option("record_format", "VB")
        .option("bdw_adjustment", -4)
        .option("is_rdw_big_endian", "true")
        .option("is_bdw_big_endian", "true")
        .option("is_rdw_part_of_record_length", true)
        .option("segment_field", "RCRD-ID")
        .option("segment_filter", "00HD01")
        .option("copybook_contents", copybookLoader("/copybooks/HEADER.cbl"))
        .load(inputFile)
```

**Comment by yruslan** [comment]
Hi Mark,

We have encountered several cases when the '-4' adjustment had to be made in order to read BDW-based data. I'm wondering if we can make it easier for people to work with such cases. I can add a paragraph to the README emphasizing that often BDWs need to be adjusted by '-4', for instance. What do you think?

**Comment by mark-weghorst** [comment]
I think it would be a good idea to make some improvements to the docs for VB including your suggestion about BDW adjustment.  

While we are on the subject of documentation, I noticed that is_bdw_big_endian is currently not listed in the documentation options.

**Comment by yruslan** [comment]
Added a little section about BDWs and RDWs
