### ISSUE TITLE
Error while reading multiple files using paths options

### ISSUE THREAD

**Issue by saikumare-a** [AbsaOSS/cobrix#544]
## Background [Optional]
Running cobrix on databricks.
Getting below error while using "Paths" option to read multiple files

JsonParseException: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)

##CODE
val df = spark.read.format("cobol").option("paths","/FileStore/tables/file1.bin").option("copybook_contents",copybook_redefines).load()
df.printSchema()

## Question
Can you help with providing whether this is correct way or there is something I am missing?

**Comment by yruslan** [comment]
Hi, please, post the full stack trace for the exception.

**Comment by saikumare-a** [comment]
Hi, Below is the full stack trace

at [Source: (String)"/FileStore/tables/file1.bin"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComment(ReaderBasedJsonParser.java:2435)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd2(ReaderBasedJsonParser.java:2410)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2361)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:671)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4340)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:359)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:273)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4186151468588413:24)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4186151468588413:79)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw$$iw$$iw$$iw.<init>(command-4186151468588413:81)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw$$iw$$iw.<init>(command-4186151468588413:83)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw$$iw.<init>(command-4186151468588413:85)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$$iw.<init>(command-4186151468588413:87)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read.<init>(command-4186151468588413:89)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$.<init>(command-4186151468588413:93)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$read$.<clinit>(command-4186151468588413)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$eval$.$print$lzycompute(<notebook>:7)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$eval$.$print(<notebook>:6)
	at $line183bd042d9b4456fa6f2de6a8bcf25db87.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:908)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:861)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:235)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:547)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:266)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:305)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:297)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:524)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:611)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:603)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:522)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:557)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:427)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:370)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:221)
	at java.lang.Thread.run(Thread.java:750)

**Comment by yruslan** [comment]
Sorry, I can't reproduce this - works fine on all versions for which Cobrix is built by default.
What is your Spark and Scala version? I can try checking this for the particular combination.

**Comment by yruslan** [comment]
Sorry, can't reproduce even on Spark 3.1.2 / Scala 2.12.

Cobrix even has a unit test for this. Maybe this can help investigate it:
https://github.com/AbsaOSS/cobrix/blob/d690236ab5865135413dbfe518eb76147aba25af/spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test28MultipartLoadSpec.scala#L65-L65

**Comment by saikumare-a** [comment]
Hi @yruslan , Thank you for the support.

we use pyspark and we dont have much knowledge on scala. can you confirm that the below 2 codes are same?

1) inputPaths = list('/Path2/File1','/Path2/File2')
.option("paths", inputPaths.mkString(",")) 
2)
.option("paths", '/Path2/File1,/Path2/File2')

**Comment by yruslan** [comment]
Yes, they seems the same.

**Comment by saikumare-a** [comment]
Hi @yruslan ,

can you try below code ( putting exact file name) and let me know the result

val input_path = "/path1/folder1/file.txt"
val df= spark.read.format("csv").option("paths",input_path).load()
df.show()

**Comment by yruslan** [comment]
I get
```
Unable to infer schema for CSV. It must be specified manually.
org.apache.spark.sql.AnalysisException: Unable to infer schema for CSV. It must be specified manually.
```
Why?

Note: `csv` and `cobol` handle multiple paths differently. The reason is Cobrix implements v1 of data source API while CSV implements v2.

**Comment by yruslan** [comment]
Is this sorted?

**Comment by saikumare-a** [comment]
still getting same issue, not sure where the issue is.

any plans to support file pattern or multiple files support using load() function

**Comment by yruslan** [comment]
Supporting multiple files in `load()` requires implementing v2 of data source interface. And it is a lot of work. So in the near future we don't have the capacity to implement it.

That is why we have `.options("paths", "path1,path2")` workaround.

There is another workaround. You can do

```
df1 = spark.read()...
df2 = spark.read()...
df3 = spark.read()...

dfFull = df1.union(df2).union(df3)
```

**Comment by saikumare-a** [comment]
thanks for the workaround.

i was thinking about below 2 steps process as workaround 
1) to read multiple files using load() and write to temporary physical file
2) then reading single temporary physical file using load()

your workaround approach saved both the processing time and storage. 

Thanks  a lot  again!!

**Comment by leandrohmvieira-db** [comment]
Just ran on the same issue, just for the record

**Comment by yruslan** [comment]
Hi @leandrohmvieira-db ,

In your case a workaround might be to read the directory:
```scala
val df = spark
            .read
            .format("cobol")                             
            .option("record_format", "V")                
            .option("copybook", copybook) 
            .load("/brd_sample/input_dir/it")
```
But this is very interesting. I'm wondering if Databricks uses 'paths' for its own logic and expects a JSON there... If this is the case we can add an additional option that will have the same meaning as 'paths')

Could you please try the latest snapshot assembly JAR if you can:
[spark-cobol-assembly-2.6.2-SNAPSHOT.zip](https://github.com/AbsaOSS/cobrix/files/10308672/spark-cobol-assembly-2.6.2-SNAPSHOT.zip)

**Comment by yruslan** [comment]
I can confirm the issue. Spark has 'paths' option that it can use for purposes of accessing v2 sources in legacy mode. It sets that option as a JSON array. This contradicts with Cobrix which uses comma separated paths.

Will fix this by adding `.option("data_paths", "/path1,path2")` extension as a workaround.

**Comment by yruslan** [comment]
The extension is added in 2.6.2

**Comment by leandrohmvieira-db** [comment]
> The extension is added in 2.6.2

Thank you @yruslan, I'm a bit of a newbie in the OSS space, so when it become available in Maven central?

**Comment by yruslan** [comment]
Usually within a couple of ours after a release.  It is available now: https://search.maven.org/artifact/za.co.absa.cobrix/spark-cobol_2.13/2.6.2/jar

**Comment by leandrohmvieira-db** [comment]
Just found out the latest Databricks version is still on Scala 2.12 😢 

https://search.maven.org/search?q=g:za.co.absa.cobrix%20AND%20a:spark-cobol_2.12%20AND%20v:2.6.2

**Comment by yruslan** [comment]
Strange that spark-cobol_2.12 is not on Maven Central yet. All variants are released together.

**Comment by leandrohmvieira-db** [comment]
Just for the record, I just tested `spark-cobol 2.6.2 scala 2.12` using the snippet below and everything is working great:

```scala
val paths = Seq("dbfs:/path/to/file0.bin","dbfs:/path/to/file2.bin","dbfs:/path/to/file_n.bin")

val copybook = "dbfs:/path/copybook.txt"

val df = spark
            .read
            .format("za.co.absa.cobrix.spark.cobol.source")                             
            .option("record_format", "V")                
            .option("copybook", copybook) 
            .option("data_paths",paths.mkString(","))
            .load()

display(df)
```
