### ISSUE TITLE
Syntax error in the copybook at line 2: Unable to parse the value of LEVEL. Numeric value expected, but 'PN-TABLE-NAME' encountered

### ISSUE THREAD

**Issue by harshitgoyal** [AbsaOSS/cobrix#76]
Hi Team,

I am getting the error while trying to create the DF.  It is failing with LAYOUT file error. 
Could you please help me to get the error in layout file.
 

Spark shell:
spark2-shell --master yarn --deploy-mode client --driver-cores 2 --driver-memory 4G --jars cobol-parser-0.4.3-SNAPSHOT.jar,spark-cobol-0.4.3-SNAPSHOT.jar,scodec-core_2.11-1.10.3.jar,scodec-bits_2.11-1.1.2.jar

Data Frame:
val df = spark.read.format("cobol").option("copybook", "/user/cloudera/layout/layout_spark.txt").load("/user/cloudera/test_mainframe/DEPEND_SAMP_190422150915.dat")

Error:
za.co.absa.cobrix.cobol.parser.exceptions.SyntaxErrorException: Syntax error in the copybook at line 2: Unable to parse the value of LEVEL. Numeric value expected, but 'PN-TABLE-NAME' encountered
  at za.co.absa.cobrix.cobol.parser.CopybookParser$.za$co$absa$cobrix$cobol$parser$CopybookParser$$CreateCopybookLine(CopybookParser.scala:204)
  at za.co.absa.cobrix.cobol.parser.CopybookParser$$anonfun$8.apply(CopybookParser.scala:134)
  at za.co.absa.cobrix.cobol.parser.CopybookParser$$anonfun$8.apply(CopybookParser.scala:133)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  at za.co.absa.cobrix.cobol.parser.CopybookParser$.parseTree(CopybookParser.scala:133)
  at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.loadCopyBook(FixedLenNestedReader.scala:81)
  at za.co.absa.cobrix.spark.cobol.reader.fixedlen.FixedLenNestedReader.<init>(FixedLenNestedReader.scala:47)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createFixedLengthReader(DefaultSource.scala:86)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.buildEitherReader(DefaultSource.scala:73)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:57)
  at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:48)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
  ... 49 elided

layout file:
       01 DCLDPN-DPND-REC-TABL.
		02 DPN-TABLE-NAME		PIC X(8).
		02 DPN-EMP-NBR			PIC S9(9) COMP.
		02 DPN-CARR-CODE		PIC X(3).
		02 DPN-ACVY-STRT-DATE	PIC X(10).
		02 DPN-CREW-ACVY-CODE	PIC X(3).
		02 DPN-PRNG-NBR			PIC X(5).
		02 DPN-PRNG-ORIG-DATE	PIC X(10).
		02 DPN-ASNT-DAYS-CNT	PIC S9(4) COMP.
		02 DPN-RVEW-DATE		PIC X(10).
		02 DPN-CONJ-ACVY-CODE	PIC X(3).
		02 DPN-NOTE-RCVD-IND	PIC X(1).
		02 DPN-DROP-OFF-DATE	PIC X(10).
		02 DPN-DPND-CMNT-TEXT	PIC X(65).
		02 FILLER				PIC X(66).

**Comment by yruslan** [comment]
Cobrix ignores first 6 characters of each line (and all characters after column 72).
The first 6 characters are often used by comments so Cobrix cannot make any assumptions about it.
Please, try adding 6 spaces in front of each line, e.g.
```
      01 DCLDPN-DPND-REC-TABL.
      02 DPN-TABLE-NAME	PIC X(8).
      02 DPN-EMP-NBR	PIC S9(9) COMP.
      02 DPN-CARR-CODE	PIC X(3).
...
```

**Comment by Ashesh1993** [comment]
Hello, I am newly parsing cobol to dataset. I am able to parse the copybook but in data file i am getting the below error. Could you pleae help me out.

Exception in thread "main" java.lang.IllegalArgumentException: There are some files in D:/data_file.txt that are NOT DIVISIBLE by the RECORD SIZE calculated from the copybook (150 bytes per record). Check the logs for the names of the files.
	at za.co.absa.cobrix.spark.cobol.source.scanners.CobolScanners$.buildScanForFixedLength(CobolScanners.scala:88)

**Comment by yruslan** [comment]
Please, raise a new issue for this conversation.
