### ISSUE TITLE
spark.read.format: Intellij vs shell

### ISSUE THREAD

**Issue by wrangel** [AbsaOSS/cobrix#84]
Hi team

Scenario 1: Spark-shell, local mode, Windows local file system.

The following ingestion works fine: 

```
spark-shell --jars D:\Tools\cobrix-master-jars\cobol-parser-0.4.2.jar,D:\Tools\cobrix-master-jars\spark-cobol-0.4.2.jar,D:\Tools\cobrix-master-jars\scodec-core_2.11-1.10.3.jar,D:\Tools\cobrix-master-jars\scodec-bits_2.11-1.1.4.jar

val df_in: DataFrame = spark.read.format("cobol"). //"za.co.absa.cobrix.spark.cobol.source"
    option("copybook", "D:\\Tools\\cobrix-master\\data\\test2_copybook.cob").
    load("D:\\Tools\\cobrix-master\\data\\test2_data\\example.bin")
df_in.count

res30: Long = 10
```

Scenario 2: Intellij Ultimate. Maven, scala-maven-plugin, and the following dependencies in the POM,

```
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.12</artifactId>
            <version>2.4.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.12</artifactId>
            <version>2.4.2</version>
        </dependency>

        <dependency>
            <groupId>za.co.absa.cobrix</groupId>
            <artifactId>spark-cobol</artifactId>
            <version>0.4.2</version>
        </dependency>
```

and creating a simple ingestion routine:

```
package XYZ

import org.apache.spark.sql._

object Main {
  def main(args: Array[String]): Unit = {
    val spark: SparkSession = SparkSession.builder().
      master("local").
      appName("cobrixTester").
      getOrCreate()

    val df_in: DataFrame = spark.read.format("cobol"). //"za.co.absa.cobrix.spark.cobol.source"
      option("copybook", "D:\\Tools\\cobrix-master\\data\\test2_copybook.cob").
      load("D:\\Tools\\cobrix-master\\data\\test2_data\\example.bin")
    df_in.count
  }
}
```

This results in:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.NoClassDefFoundError: scala/Product$class
	at za.co.absa.cobrix.spark.cobol.source.parameters.CobolParameters.<init>(CobolParameters.scala:50)
	at za.co.absa.cobrix.spark.cobol.source.parameters.CobolParametersParser$.parse(CobolParametersParser.scala:118)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:54)
	at za.co.absa.cobrix.spark.cobol.source.DefaultSource.createRelation(DefaultSource.scala:48)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at XYZ.Main$.main(Main.scala:14)
	at XYZ.Main.main(Main.scala)
	... 5 more
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

```
for both `.format("cobol")` and `.format("za.co.absa.cobrix.spark.cobol.source")`

Thanks for your inputs 
Matthias

**Comment by yruslan** [comment]
Thanks for the bug report!
The reason for the errors is that Scala 2.12 is not supported yet.
Please, try `spark-core_2.11` and `spark-sql_2.11`  for `<version>2.4.2</version>`, e.g. Scala 2.11.
This definitely needs to be solved in the near future. Will add a separate issue for that.

**Comment by wrangel** [comment]
That was it. Thanks!
